# Generated by Django 3.0.6 on 2020-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='pic_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='pic_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
