# Generated by Django 3.0.6 on 2020-07-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200724_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='pic_height',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='pic_width',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.URLField(blank=True, null=True)),
                ('pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pic_width', models.PositiveIntegerField(blank=True, null=True)),
                ('pic_height', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='basic_app.UserProfileInfo')),
            ],
        ),
    ]
