# Generated by Django 3.0.6 on 2020-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20200731_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pic_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pic_width',
        ),
        migrations.AddField(
            model_name='photo',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pic_Number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
