# Generated by Django 3.0.6 on 2020-07-31 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20200731_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='pic_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pic_width',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='photo',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pic_Number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='basic_app.UserProfileInfo'),
        ),
    ]
